Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
  ubuntu.vm.box = "geerlingguy/ubuntu2004"
  ubuntu.vm.network "public_network"
  ubuntu.vm.synced_folder "../data", "/vagrant_data"
  ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
      ubuntu.vm.provision "shell", inline: <<-SHELL
       apt update
       apt install apache2 wget unzip -y
       systemctl start apache2
       systemctl enable apache2
       cd /tmp/
       wget https://www.tooplate.com/zip-templates/2121_wave_cafe.zip
       unzip -o 2121_wave_cafe.zip
       cp -r 2121_wave_cafe/* /var/www/html/
       systemctl restart apache2
   SHELL
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "geerlingguy/centos7"
    centos.vm.network  "public_network"
    centos.vm.synced_folder "../data", "/vagrant_data"
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    centos.vm.provision "shell", inline: <<-SHELL
      yum install mariadb-server -y
      systemctl start mariadb 
      systemctl enable mariadb

      mysql -u root -e 'CREATE DATABASE wordpress;'
      mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "123";'
      mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      mysql -u root -e 'FLUSH PRIVILEGES;'
   SHELL
  end
end
